stages:
  - build

build-and-push:
  stage: build
  image: docker:24
  services:
    - name: docker:24-dind

  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -t my_img .
    - docker run -p 5000:5000 --name my_img my_cont