stages:
  - build
  - diff
  - deploy

build:
  stage: build
  image: docker:24
  services:
    - name: docker:24-dind
  before_script:
    - echo "$HAWK_REGISTRY_PASSWORD" | docker login -u "$HAWK_REGISTRY_USER" --password-stdin "$HAWK_REGISTRY"
    - docker context create context
    - docker buildx create --name mybuilder --driver docker-container --use context
  script:
    - TAGS="$HAWK_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - if [ -n "$CI_COMMIT_TAG" ]; then TAGS="$HAWK_REGISTRY_IMAGE:$CI_COMMIT_TAG"; fi
    - docker buildx build --platform linux/amd64,linux/arm64 -f ./Dockerfile ./ -t $TAGS --push
    - echo "TAGS=${TAGS}" > tags.env
  rules:
    - if: "$CI_COMMIT_TAG"
      when: always
    - when: manual

  artifacts:
    reports:
      dotenv: tags.env  

diff:
  stage: diff
  image: 
    name: alpine/k8s:1.29.4
    entrypoint: [""] 

  variables:
    NAMESPACE: "ia331"

  script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG" > ~/.kube/config

    - helm template ia331s08-app ./chart --namespace "$NAMESPACE" --set image="$TAGS" | kubectl diff -n "$NAMESPACE" -f - || true


deploy:
  stage: deploy
  image: 
    name: alpine/helm:3.12.3
    entrypoint: [""]  

  variables:
    RELEASE_NAME: "ia331s08-app"

  script:
    - echo "DEPLOY WITH TAG $TAGS"
    - echo "$KUBECONFIG"
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG" > ~/.kube/config
    - helm upgrade --install "$RELEASE_NAME" ./chart --namespace ia331 --set image="$TAGS"

  rules:
    - when: manual