apiVersion: apps/v1
kind: Deployment
metadata:
  name: ia331s08-app
  namespace: ia331
  labels:
    owner: ia331s08
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ia331s08-app
  template:
    metadata:
      labels:
        app: ia331s08-app
        owner: ia331s08
    spec:
      serviceAccountName: ci
      containers:
        - name: ia331s08-app
          image: cr.hawk.csc.sibsutis.ru/hawk-dev/ia331s08-distrarchapp:v1
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "32Mi"
              cpu: "32m"
            limits:
              memory: "64Mi"
              cpu: "64m"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20