apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://api.hawk.csc.sibsutis.ru:6446
    insecure-skip-tls-verify: true
  name: hawk-dev
- cluster:
    server: https://api.hawk.csc.sibsutis.ru:6445
    insecure-skip-tls-verify: true
  name: hawk
users:
- name: ia331s08
  user:
    auth-provider:
      config:
        client-id: dex-hawk-all-in-one-1
        client-secret: wl7F2XeGZSKlsdJJh35AwiQIL2CBaVwv1NEHtnzetXqV8tzi
        id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjQxYmEyNzQ4YWZhOWI2MDdhYTdjYzY3NGRkYzkzMmMxMDZlMTA0ZjcifQ.eyJpc3MiOiJodHRwczovL2RleC5oYXdrLmNzYy5zaWJzdXRpcy5ydSIsInN1YiI6IkNrRjFhV1E5YVdFek16RnpNRGdzWTI0OWRYTmxjbk1zWTI0OVlXTmpiM1Z1ZEhNc1pHTTlhWEJoTEdSalBXTnpZeXhrWXoxemFXSnpkWFJwY3l4a1l6MXlkUklFYkdSaGNBIiwiYXVkIjoiZGV4LWhhd2stYWxsLWluLW9uZS0xIiwiZXhwIjoxNzY0OTIyNDYyLCJpYXQiOjE3NjQ4MzYwNjIsImF0X2hhc2giOiJUaDA3LU53QkVLSUx3N2VnSWJqamhnIiwiY19oYXNoIjoiQkVZSnJ2VmM5dS1pdXg2Zk9BQUhpUSIsImVtYWlsIjoiaWEzMzFzMDhAY3NjLnNpYnN1dGlzLnJ1IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImdyb3VwcyI6WyJpYTMzMSIsImhhd2stYWNjZXNzIl0sIm5hbWUiOiJpYTMzMXMwOCIsInByZWZlcnJlZF91c2VybmFtZSI6ImlhMzMxczA4In0.JS84C45px6FF-546V8j1WQfDyowsIu0B47LP_cn1wCDqNtZ0UAVpSy8U9LrEkVQQPn1rSNNGuNw_HIQHST7-L6793XFTTmoKpPn0zcU50C23OXqMC5Dg14lhpKFw7VJT3bc5-PgEDlW_OAkIsr4hg6lKUX7zHKCdSt_cub5OgeHkh6BFD85xm-qcuyqK0AidXD9p8QHjb59wjur5k9jnXTKVitZf1DKT95a4wSVPV_XlXPB6NamoNnPxqF7922zLCanQg3RuVGLNlxToO6Z_7n7QhXRzRZs1Ww-PjZW_CzyyBAqCttQYCYncO-QCFSgo38bqDRI3H06abz6OWU1WYg
        idp-issuer-url: https://dex.hawk.csc.sibsutis.ru
        refresh-token: Chl0Z3I0Y2c1bW53aHQ0aWltZ211NHZ2YWZjEhlnN3Z2b3JvdzM0d2QyZGkybzNlN3VncWdt
      name: oidc
contexts:
- context:
    cluster: hawk-dev
    user: ia331s08
  name: hawk-dev
- context:
    cluster: hawk
    user: ia331s08
  name: hawk
current-context: hawk-dev