apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://api.hawk.csc.sibsutis.ru:6446
    insecure-skip-tls-verify: true
  name: hawk-dev
- cluster:
    server: https://api.hawk.csc.sibsutis.ru:6445
    insecure-skip-tls-verify: true
  name: hawk
users:
- name: ia331s08
  user:
    auth-provider:
      config:
        client-id: dex-hawk-all-in-one-1
        client-secret: wl7F2XeGZSKlsdJJh35AwiQIL2CBaVwv1NEHtnzetXqV8tzi
        id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjgzYjJlY2ViNmQwNzkxOTBmYjc0ZjYzYWM4NzM2ZmQwMDg5ZGNjMDYifQ.eyJpc3MiOiJodHRwczovL2RleC5oYXdrLmNzYy5zaWJzdXRpcy5ydSIsInN1YiI6IkNrRjFhV1E5YVdFek16RnpNRGdzWTI0OWRYTmxjbk1zWTI0OVlXTmpiM1Z1ZEhNc1pHTTlhWEJoTEdSalBXTnpZeXhrWXoxemFXSnpkWFJwY3l4a1l6MXlkUklFYkdSaGNBIiwiYXVkIjoiZGV4LWhhd2stYWxsLWluLW9uZS0xIiwiZXhwIjoxNzYzOTcxMjEzLCJpYXQiOjE3NjM4ODQ4MTMsImF0X2hhc2giOiIxNGNKYXBBYnVCSmNjcHBtRGFjcy1nIiwiY19oYXNoIjoiazZicU5zSHdXNlZwc2NVZ2VvNk5ZUSIsImVtYWlsIjoiaWEzMzFzMDhAY3NjLnNpYnN1dGlzLnJ1IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImdyb3VwcyI6WyJpYTMzMSIsImhhd2stYWNjZXNzIl0sIm5hbWUiOiJpYTMzMXMwOCIsInByZWZlcnJlZF91c2VybmFtZSI6ImlhMzMxczA4In0.iyfxWLcam-ntpy77mf2wajGYOlhY6WJ6FpJxZOLJnx5WDbUEA_M_MQ2MZOR8-3VCAhJ2yp_i6oUzWv1FvVwoIqM-bngooDsos15al_6zcLw1hAd-Ycmw261YAsenp8xnOalEUqxkdFfMDD0zQG6f37rehMj-jDu4NSFV3lN8N-xTt9X_5-ujPzSaU38vr_ahTMQCr2yifYB25Df6jRMKskF2qlf6kme2fqNkGHWLfoIKBWpMW8tAn701Q3mBP_tWNRxjEbO1mr8fFjcrMXdp6kZM8nrp1VQahEYh8VAAaOIKnSWyv4xYKYg7i4RCNkYY_0pDdSW2kER3u_aaF6GPag
        idp-issuer-url: https://dex.hawk.csc.sibsutis.ru
        refresh-token: ChlzM2tlNjMyN3hkb2I3Zmd1bnB4cG9oa2R3Ehlkb2l4emEzN2k1NnU2dXdiNDdra2pndG9h
      name: oidc
contexts:
- context:
    cluster: hawk-dev
    user: ia331s08
  name: hawk-dev
- context:
    cluster: hawk
    user: ia331s08
  name: hawk
current-context: hawk-dev